
-----INSERTAR DATOS EN TRATAMIENTO-------
CREATE OR REPLACE FUNCTION TRATAMIENTO_FK(
ID_TRATAMIENTo NUMBER,
NOMBRE_TRATAMIENTo VARCHAR2,
DESCRIPCIOn VARCHAR2
)
RETURN NUMERIC
IS
BEGIN
    INSERT INTO TRATAMIENTO (ID_TRATAMIENTO, NOMBRE_TRATAMIENTO, DESCRIPCION) VALUES (ID_TRATAMIENTO,NOMBRE_TRATAMIENTO,DESCRIPCION);
    COMMIT ;
   RETURN ID_TRATAMIENTo;
end;

-----------INSERTAR DIAGNOSTICO -----------
CREATE OR REPLACE FUNCTION DIAGNOSTICO_FK(
ID_DIAGNOSTICo NUMBER,
DESCRIPCIOn VARCHAR2
)
RETURN NUMERIC
IS
BEGIN
    INSERT INTO DIAGNOSTICO VALUES (ID_DIAGNOSTICO,DESCRIPCION);
    COMMIT;
    RETURN ID_DIAGNOSTICo;
end;

-------------INSERTAR DATOS EN RECETAMEDICA-------------
    CREATE OR REPLACE FUNCTION RECETAMEDICA_FK(
ID_RECETAMEDICa NUMERIC,
NOMBRE_MEDICAMENTo VARCHAR2,
INDICACIONEs VARCHAR2
    )
    RETURN NUMERIC
IS
BEGIN
    INSERT INTO RECETAMEDICA(ID_RECETAMEDICA, NOMBRE_MEDICAMENTO, INDICACIONES) VALUES (ID_RECETAMEDICA,NOMBRE_MEDICAMENTO,INDICACIONES);
COMMIT;
RETURN ID_RECETAMEDICa;
END ;

---------------INSERTAR DATOS CITA MEDICA -----------------
CREATE OR REPLACE FUNCTION CITA_MEDICA_FK(
ID_CITA NUMBER,
HORA_CITA VARCHAR2,
FECHA_CITA VARCHAR2,
MEDICO_CEDULA_MEDICo VARCHAR2,
PACIENTE_CEDULA_PACIENTE VARCHAR2
)
RETURN NUMERIC
IS
BEGIN
    INSERT INTO CITA_MEDICA VALUES (ID_CITA,HORA_CITA,FECHA_CITA,MEDICO_CEDULA_MEDICO,PACIENTE_CEDULA_PACIENTE);
COMMIT;
RETURN ID_CITA;
end;

    --------   INGRESAR DATOS CONSULTA MEDICA --------------
    CREATE OR REPLACE PROCEDURE CONSULTA_MED(


    )
    RETURN NUM

DECLARE
  MESSAGE_TRATAMIENTO NUMERIC:= TRATAMIENTO_FK(ID_TRATAMIENTO.nextval,'QUIMIOTERAPIA','CADA 1 MES');
  MESSAGE_DIAGNOSTICO NUMERIC := DIAGNOSTICO_FK(ID_DIAGNOSTICO.nextval,'CITA MEDICA CADA 1 MES');
  MESSAGE_RECETAMEDICA NUMERIC := RECETAMEDICA_FK(ID_RECETAMEDICA.nextval,'ACETAMINOFEN','TOMAR 1 VEZ CADA 12 HR');
  MESSAGE_CITA NUMERIC := CITA_MEDICA_FK(ID_CITA.nextval,'12:00','2022-09-09','1193540102','1134567304')
BEGIN
DBMS_OUTPUT.PUT_LINE(MESSAGE_TRATAMIENTO,MESSAGE_DIAGNOSTICO,MESSAGE_RECETAMEDICA);
end;