
----------------------------------------  INSERTAR DATOS EN TRATAMIENTO -------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE TRATAMIENTO_FK(
V_IDTRATAMIENT0 TRATAMIENTO.ID_TRATAMIENTO%TYPE,
V_NOMBRE_TRATAMIENT0 TRATAMIENTO.NOMBRE_TRATAMIENTO%TYPE,
V_DESCRIPCION TRATAMIENTO.DESCRIPCION%TYPE
)
IS
BEGIN
    INSERT INTO TRATAMIENTO (ID_TRATAMIENTO, NOMBRE_TRATAMIENTO, DESCRIPCION) VALUES (V_IDTRATAMIENT0,V_NOMBRE_TRATAMIENT0,V_DESCRIPCION);
    COMMIT ;
end;

--------------------------------------------------------INSERTAR DIAGNOSTICO --------------------------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE DIAGNOSTICO_FK(
V_DIAGNOSTICO DIAGNOSTICO.ID_DIAGNOSTICO%TYPE,
V_DESCRIPCION DIAGNOSTICO.DESCRIPCION%TYPE
)

IS
BEGIN
    INSERT INTO DIAGNOSTICO VALUES (V_DIAGNOSTICO,V_DESCRIPCION);
    COMMIT;
end;

-----------------------------------------------------INSERTAR DATOS EN RECETAMEDICA-----------------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE RECETAMEDICA_FK(
V_RECETAMEDICA RECETAMEDICA.ID_RECETAMEDICA%TYPE,
V_MEDICAMENTO RECETAMEDICA.NOMBRE_MEDICAMENTO%TYPE,
V_INDICACIONES RECETAMEDICA.INDICACIONES%TYPE
    )
IS
BEGIN
    INSERT INTO RECETAMEDICA(ID_RECETAMEDICA, NOMBRE_MEDICAMENTO, INDICACIONES) VALUES (V_RECETAMEDICA,V_MEDICAMENTO,V_INDICACIONES);
COMMIT;
END ;

---------------------------------------------------------INSERTAR DATOS CITA MEDICA -------------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CITA_MEDICA_FK(
V_CITA CITA_MEDICA.ID_CITA%TYPE,
V_HORA_CITA CITA_MEDICA.HORA_CITA%TYPE,
V_FECHA_CITA CITA_MEDICA.FECHA_CITA%TYPE,
V_MEDICO_CEDULA CITA_MEDICA.MEDICO_CEDULA_MEDICO%TYPE,
V_CEDULA_PACIENTE CITA_MEDICA.PACIENTE_CEDULA_PACIENTE%TYPE
)

IS
BEGIN
    INSERT INTO CITA_MEDICA VALUES (V_CITA,V_HORA_CITA,V_FECHA_CITA,V_MEDICO_CEDULA,V_CEDULA_PACIENTE) ;
COMMIT;
end;



--------------------REGISTRAR PACIENTE -------------------------------------

CREATE OR REPLACE PROCEDURE RE_PACIENTE(
V_CEDULA PACIENTE.CEDULA_PACIENTE%TYPE,
V_PRIMERNOM PACIENTE.PRIMER_NOMBRE%TYPE,
V_SEGUNDONOM PACIENTE.SEGUNDO_NOMBRE%TYPE,
V_PRIMERAPE PACIENTE.PRIMER_APELLIDO%TYPE,
V_SEGUNDOAPE PACIENTE.SEGUNDO_APELLIDO%TYPE,
V_TELEFONO  PACIENTE.TELEFONO%TYPE,
V_CORREO   PACIENTE.CORREO_ELECTRONICO%TYPE,
V_DIRECCION PACIENTE.DIRECCION%TYPE,
V_SEXO  PACIENTE.SEXO%TYPE,
V_CIUDAD PACIENTE.CIUDAD%TYPE

)
AS
BEGIN
INSERT INTO PACIENTE(CEDULA_PACIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, TELEFONO, CORREO_ELECTRONICO, DIRECCION, SEXO, CIUDAD)
VALUES (V_CEDULA,V_PRIMERNOM,V_SEGUNDONOM,V_PRIMERAPE,V_SEGUNDOAPE,V_TELEFONO,V_CORREO,V_DIRECCION,V_SEXO,V_CIUDAD);
end;

    --------------------REGISTRAR MEDICO -------------------------------------

    CREATE OR REPLACE PROCEDURE RE_MEDICO(
V_CEDULA MEDICO.CEDULA_MEDICO%TYPE,
V_PRIMERNOM MEDICO.PRIMER_NOMBRE%TYPE,
V_SEGUNDONOM MEDICO.SEGUNDO_NOMBRE%TYPE,
V_PRIMERAPE MEDICO.PRIMER_APELLIDO%TYPE,
V_SEGUNDOAPE MEDICO.SEGUNDO_APELLIDO%TYPE,
V_TELEFONO  MEDICO.TELEFONO%TYPE,
V_CORREO   MEDICO.CORREO_ELECTRONICO%TYPE,
V_DIRECCION MEDICO.DIRECCION%TYPE,
V_SEXO  MEDICO.SEXO%TYPE,
V_CIUDAD MEDICO.CIUDAD%TYPE
)
AS
BEGIN
INSERT INTO MEDICO VALUES (V_CEDULA,V_PRIMERNOM,V_SEGUNDONOM,V_PRIMERAPE,V_SEGUNDOAPE,V_TELEFONO,V_CORREO,V_DIRECCION,V_SEXO,V_CIUDAD);
end;

-------------------------------------------------------------   INGRESAR DATOS CONSULTA MEDICA --------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE INSERTAR_CONSULTA(
V_NEXT CONSULTA.ID_CONSULTAMEDICA%TYPE,
V_PESO CONSULTA.PESO%TYPE,
V_ESTATURA CONSULTA.ESTATURA%TYPE,
V_PRESION CONSULTA.PRESION_ARTERIAL%TYPE,
V_RITMO CONSULTA.RITMO_CARDIACO%TYPE,
V_ANTECEDENTES CONSULTA.ANTECEDENTES_QUIRURJICOS%TYPE,

V_TRATAMIENTO CONSULTA.TRATAMIENTO_ID_TRATAMIENTO%TYPE,
V_DIAGNOSTICO CONSULTA.DIAGNOSTICO_ID_DIAGNOSTICO%TYPE,
V_RECETA CONSULTA.RECETAMEDICA_ID_RECETAMEDICA%TYPE,
V_CITA CONSULTA.CITA_MEDICA_ID_CITA%TYPE,

V_MEDICO CONSULTA.MEDICO_CEDULA_MEDICO%TYPE
)
IS
BEGIN
    
INSERT INTO CONSULTA(ID_CONSULTAMEDICA, PESO, ESTATURA, PRESION_ARTERIAL, RITMO_CARDIACO, ANTECEDENTES_QUIRURJICOS, TRATAMIENTO_ID_TRATAMIENTO, DIAGNOSTICO_ID_DIAGNOSTICO, RECETAMEDICA_ID_RECETAMEDICA, CITA_MEDICA_ID_CITA, MEDICO_CEDULA_MEDICO)
VALUES (V_NEXT,V_PESO,V_ESTATURA,V_PRESION,V_RITMO,V_ANTECEDENTES,V_TRATAMIENTO,V_DIAGNOSTICO,V_RECETA,V_CITA,V_MEDICO);
COMMIT ;
end;



-----------------------------REGISTRAR AGENDA -------------------------------------
CREATE OR  REPLACE PROCEDURE REGISTRAR_AGE(
V_ID AGENDA.ID_AGENDA%TYPE,
V_CITA_ID AGENDA.CITA_MEDICA_ID_CITA%TYPE,
V_DETALLE_ID AGENDA.DETALLEAGENDA_ID_DETALLE%TYPE,
V_MEDICO AGENDA.MEDICO_CEDULA_MEDICO%TYPE
)
IS
BEGIN
INSERT INTO AGENDA VALUES (V_ID,V_CITA_ID,V_DETALLE_ID,V_MEDICO);
end;

-----------------------------------------REGISTRAR HORARIO -----------------------------------------------------------------------------
    CREATE OR REPLACE PROCEDURE HORARIO_FK(
V_HORARIO HORARIO.ID_HORARIO%TYPE,
V_HORA_INICIAL HORARIO.HORA_INICIAL%TYPE,
V_HORAFINAL HORARIO.HORA_FINAL%TYPE
)

IS
BEGIN
INSERT INTO HORARIO VALUES (V_HORARIO,V_HORA_INICIAL,V_HORAFINAL);
COMMIT ;

end;

------REGISTRAR DETALLE AGENDA ---------------------------
CREATE OR REPLACE PROCEDURE DETALLEAGENDA_FK(
V_DETALLE DETALLEAGENDA.ID_DETALLE%TYPE,
V_FECHA_DISPONIBLE DETALLEAGENDA.FECHA_DISPONIBLE%TYPE,
V_FECHA_FINAL DETALLEAGENDA.FECHA_FINAL_ATENCION%TYPE,
V_ESTADO DETALLEAGENDA.ESTADO%TYPE,
V_HORARIO DETALLEAGENDA.HORARIO_ID_HORARIO%TYPE,
V_MEDICO DETALLEAGENDA.MEDICO_CEDULA_MEDICO%TYPE
)

IS

BEGIN
INSERT INTO DETALLEAGENDA VALUES(V_DETALLE,V_FECHA_DISPONIBLE,V_FECHA_FINAL,V_ESTADO,V_HORARIO,V_MEDICO);

end;
------------------------------------------------------ ELIMINAR MEDICO    ----------------------------------------------
CREATE OR REPLACE PROCEDURE ELIMINAR_MEDICO(
ID_MED IN VARCHAR2
)
IS
    V_CEDULA MEDICO.CEDULA_MEDICO%TYPE := ID_MED;
BEGIN
 DELETE  FROM MEDICO WHERE CEDULA_MEDICO := V_CEDULA;
end;

-------------------------------------------------------- ELIMINAR PASIENTE -------------------------------------------------------

CREATE OR REPLACE PROCEDURE ELIMINAR_PACIENTE(
ID_PAC IN VARCHAR2
)
IS
    V_CEDULA PACIENTE.CEDULA_PACIENTE%TYPE := ID_PAC;
BEGIN
 DELETE  FROM MEDICO WHERE CEDULA_MEDICO := V_CEDULA;
end;